name: Test
description: "what's up microsoft?"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  cache-target:
    default: /root/.cache/go-build
    description: "Where the cache is stored in the docker container. Default: `/root/.cache/go-build`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: TEST
      shell: bash
      run: |
        echo cache-source: ${{ inputs.cache-source }}
        echo cache-target: ${{ inputs.cache-target }}
        echo scratch-dir: ${{ inputs.scratch-dir }}
